# Copy your Score(Motifs), Count(Motifs), Profile(Motifs), and Consensus(Motifs) functions here.
def Consensus(Motifs):
    ''' gives a sequence with the most similar nt for all seq in the Motif '''
    k = len(Motifs[0])
    count = Count(Motifs)
    consensus = ""
    for j in range(k):
        m = 0
        frequentSymbol = ""
        for symbol in "ACGT":
            if count[symbol][j] > m:
                m = count[symbol][j]
                frequentSymbol = symbol
        consensus += frequentSymbol
    return consensus

def Count(Motifs):
    ''' make a dictionary that contains the number of nt in a column '''
    count = {} # initializing the count dictionary
    k = len(Motifs[0])
    for symbol in "ACGT":
        count[symbol] = []
        for j in range(k):
             count[symbol].append(0) # start with 0 for nt of each column               
    t = len(Motifs)
    for i in range(t):
        for j in range(k):
            symbol = Motifs[i][j]
            count[symbol][j] += 1 # add 1 when encountering a similar nt     
    return count

def Score(Motifs):
    ''' calculates the score/differences found '''
    score = 0 # initialize score
    consensus = Consensus(Motifs)
    count_motif = list(Motifs)

    # count the number of differences between the consensus and sequence
    for seq in count_motif:
        for i in range(len(seq)):
            if seq[i] != consensus[i]:
                score += 1
    return score

def Profile(Motifs):
    ''' calculates the profile in decimals '''
    profile = {}
    counted = Count(Motifs)
    t = len(counted)

    for symbol in "ACGT":
        profile[symbol] = []   
        for j in range(len(counted[symbol])):
            coordinate = counted[symbol][j]
            num = float(coordinate)/10
            profile[symbol].append(num)
    return profile

# Then copy your ProfileMostProbableKmer(Text, k, Profile) and Pr(Text, Profile) functions here.
def Pr(Text, Profile):
    ''' calculates the probability of getting a certain kmer '''
    prob = 1.0
    for i in range(len(Text)):
        key = str(Text[i])
        prob = prob * Profile[key][i]
    return prob

def ProfileMostProbableKmer(text, k, profile):
    max_prob = -1.0  # Initialize max probability as a negative value
    most_prob = "" # initialize most probable kmer
    for i in range(len(text) - k + 1):
        kmer = text[i:i+k]
        prob = Pr(kmer, profile)  
        if prob > max_prob:
            max_prob= prob
            most_prob = kmer
    return most_prob

# Input:  A list of kmers Dna, and integers k and t (where t is the number of kmers in Dna)
# Output: GreedyMotifSearch(Dna, k, t)
def GreedyMotifSearch(Dna, k, t):
    n = len(Dna[0])
    best_motifs = [Dna[i][0:k] for i in range(t)]
    for i in range(n - k + 1):
        motifs = [Dna[0][i:i+k]]
        for j in range(1, t):
            profile = Profile(motifs[0:j])
            motifs.append(ProfileMostProbableKmer(Dna[j], k, profile))
 
        if Score(motifs) < Score(best_motifs):
            best_motifs = motifs
    return best_motifs

genome = 'AATTAACACATCAGGGCTTAAGCCAGCCGGAATCAGCGTAGAGCTGACCTCGTCAGCGATTCTCGGCACGATGCGGACTCGCCTATAGCAATATCGCCGGAATAAAGGTCGGTGAATCTACCAACAGGAAGAAGATTCCCGGCTTTGATCATCGCG CATAACATAATAGGGTCCCAACCTACCATGTGAGATTCTCGCTAACATACCCGTTATCAAAGCCATTCTTCAACGACAAGCTGAGGCACGACTCGTGTAAGCAGCCGACAAGTCGTTACTACCCCGCTTCAACGGTCTTAAGCCCCACCAGTTCGG GGACTCTAGCTAAGCCGAAATCATGCATCACCCAGGCCCACCGAAAGATCTCTGGGACTTTCTTGCCTCTTCTATTCCCCTTGCTAATCGGTTGAGATGGACCGAGACGCGAACGCTTCAAAAAGTCTGAAACCCGTGGGTGGCTTCACATAATCT ATCCGGTATCACGGTCTGGAAACACACTGAGAATGGGGCTACAGCCTCGTAGTTAAATAATACAGCTAGCACTTTATAATGGTCTAATTGTTATCCCGACGGCTTCCTATTGCACTATGATCCTGAAACCACAGTCCGATACTGTTGCTGGATTCC ATTAGCCCGTCAGGTCCTATACCCATAAACGTCAAATGCTTGTGCAGAGAAGCGAACAGTTTATGTCGACGCCGACTACACATAACCCGTTATCAACAAGGGAGGCGGAACCCAATGAGCTCAGTCCAAACACGACGCGGCACAAACCTCTAGCTT TTTGCCCCGCAGTCCTAGGAGGGGTCTTGTACCTTGGCTGCAATGTTATGAGTAAATGTTTTTCGAAGCTACTCTTTCGATAAACGGGTTTGGGGCAACAAGCCTACAAGCCGGTATCATCTAAAAGAACTCGGCCTCATAGTAATATATGCTGAG GTAGAAAGAAGTGCAATTGAACCGAGTAGCCGATTATCGTAAAATGGACACAATCTGGTCACAAGAGTGAAACCTTTTCCTACCGGAGCCTCGCTACTCGTTTGGGAAAGACCAGTGGGTACCCGTAATCATGTTTCCCAAACGGGCTGCTCCTCT TCGGACAGAACTGTGCCCAAGTGGATCCGTGATCAATGCGACTTTTGTCCGGAAATGCCGGGTGAAGTCCGTGCGTGCGTTAAACACAGCCTTAGCGCGGATCCCTGCGATGCTTGAAGATTTAAGATCTGGGCCATCTAGCAACAGAGTTCACGA TTTGTCGCCATGATCTCCGAGCAAAACCGGCATCACGTATTTGCTCTCGGATCCTGTCCCGACCACCAGTAAAACCGTTACAGCTTTAAACCCCGACCACTGATCCTACCGCAGGCGCGGTCTCGGATAAAATGGTGGGAGGCCAGTACATCGCAG AGTAACGACATCTACGCGTTTCACAACCGATATCACCGACCACACTCATAGGGCGCGTGCACGTGTATGTGAAGAGGTAGTCTGGCGACAGCCGACCTGGGGCATTAGGAGTTTGAGGAAAGACTAATTTTTATTTTGCATCGCCGTGTCAATGCC CGTCGCCCACGCCATTGCCACTGCATCCGTCATCATTTTGCCTGATCTCGTCCTTGGCCCGACTAATCTAAAGAATCTTATCAGTCAACGTTCTGGATGCGCCCTCAGCCAAACGGTTTACGCTCACAGCGTGATCAGCAGGAGATATTCATTCTT GCCCACTGATTTACCCGGTTACTACTGTTAAGCCTGTGGGGAGTGTGCTCAGTATACAGGCGCACTGGCAGTCCTTCAGGACAAGACAAAAATCCGATCCGGGATCAATAGTTCAGTAATTCCGTCCGCGCTTAAGAAATCGTCGATAAGTCCATC ATCCGTCATCAACGTTCGAAGACCTGTTTTTGCTGTTCACTCATCGTGGTTAGGCCTGTGTTAGGTGGGCCTACTACTACATGATGACGCCATACTAGCGCCCTCATCAAAGTATAATCTGTGTGCTGGGTACAGAAACATAGATCACGGCCCCTG ACCCGACATCAAGTACCGCCAATTATACTGAGTCGGCTATAATAACGTTAATCACAAAATATCTACGAAGCCCTTGCCAGATCCGTTCTCCTAACGTCCCTCGCTATACCTGTCCGCCTTCTCATGGGTGGCTTCCAGTAGCAATAGTATCAGCCT TATAGGACGCGTACGCAAGCAGACAACCAGCACCCTAAGATGTACGATCCTAATCGAATTGAGTTAGACTTGTCAGGGGCCAGGGCACTGCAATAAACCGCTTGTCTGGCTCCAATCCGATCCTAAAGACGCTAGTGCCGCCTCAACCGGTATCAT GCAGGCTTTGTAAAGATATTTAGTAATTGACGAACATGTTCCTGCGTTCTGACTGGCGCAAACCGAGATCAGATATTGCTCCTCGATCTGGTTCGCGAGTGCCGCAAAGACATGAAGGCTACTAGGTATCCCACGATCAGGGGCGGACGAACTGGC ATCCGAAATCAGCATAGAAAGGTACGAACCCGGGGGCCCAAAGTTGAAAGGGCACTAATTTAAAGGCAATCAAAGGCCAAAAAGCGTAGACAGTGTTGGAGCGCTATCTCATCACAGCGAAGCAGGTGGGTATTACCAACACGGGCCTGGACGAAA GAACTCTAGATATCTTCCCACAGCAAGCAAATCACTACGGAGCATCCGTGCTGAGGATTTGAAACTGTGGGAGTGTAGCGATTTATCCGATATCACCACTCTCCCTAATACTCCACTAGCGCCAGCTTGGTGCTGCTCACCGATCGCACGTCCTAG GAATCGTGACCTGACATCAGCGGACGTATATCTTGTTCTATTCAGAGGAGCCGTTATCAACGCCCTTAGCGGTAAGGTGTGTGTACAAGCCCTTCTATTGGTTGGGGATAACACCCCCCGCCTCAGATATATGATTTTCGTCGAGAGGGCGCGCTT GAAGTTTGCCCAGGGTGTGCAGTTTGCTGGCCCTAGTTTACCGACATTTGACGAACTTATACCAACGAAGTCCAGTCAGGAATATATACATTCCTGTACAAACGCTGCGATGTTATTAAGACCCGCAATCATAGGAAGGGTCTGTAGAAAAGGCTA ATCCGCGATCATCGCTGGTCTTTTGCGGTTGCAAAGTATTATGTAAGATGAGAGGAGAGAGGACTGTCGGAGGGATCATAGTCCCTGTTATAGACGGTAGAATGGCTTTGTAACGGTCAAGTGTCATACAACGATCATGCAAATCGCGGTCAACAC TCGCGATAATCCATTTTTGGGACTACCATCCCGACAGTGTAATCTCCAACAGTACCGGCGTAGGTTATCATAGGTGAACTACCAGGAATGCCGCGCGTTATATTGACTACCCCCCGGATGACTGTATTTCTATAACGCGGAAGAAACCGCAATCAT AACCGCCATCAGTTAATGTCGCTCGACTGGGGTCTTCCAGCCTTAGTTAGGATATCCCTCCTTGTGTTACGGTAGCCCATCCATTAGCGAACTCATTAGGCACTCTGTAATAATGACACGCCGCACTGGTGAATGAAAGAATTAGAGCAAGAGTGT ATGGCCTCGAGCTGTACCTCGAGCCTAACCGTGCGCTCTTACTTGCTGGGTTCATGAAGGAACCGAAATCACGTGATTTTTTGACTTCTCAAATAACGGTTACAGCACCTTACATGGCCCTCCTCTGATAAGAATAAGAAACTGCTCGTGGATACT ACGGTTGTCACTGAGCCATGGGTTGAGGCACAGGAAGCGGCTACGAACAAATTACGCGGTTTAATTTCTGCTATCCGTTATCAGCTTCGCCTTAATGTGTTTCCTACGCCGCGCCAATAGGAGCTTGAATCCCTTCTGTGGTGATGGACAAATAGT'
dna = genome.split(' ')
k = 12
t = 25

print(' '.join(GreedyMotifSearch(dna, k, t)))

